type XhrHandler = ((this: NetworkXMLHttpRequest, ev: Event) => unknown) | null;
export declare class NetworkXMLHttpRequest extends EventTarget {
    #private;
    static readonly UNSENT = 0;
    static readonly OPENED = 1;
    static readonly HEADERS_RECEIVED = 2;
    static readonly LOADING = 3;
    static readonly DONE = 4;
    onabort: XhrHandler;
    onerror: XhrHandler;
    onload: XhrHandler;
    onloadend: XhrHandler;
    onloadstart: XhrHandler;
    onprogress: ((this: NetworkXMLHttpRequest, ev: ProgressEvent<EventTarget>) => unknown) | null;
    onreadystatechange: XhrHandler;
    ontimeout: XhrHandler;
    timeout: number;
    withCredentials: boolean;
    responseType: XMLHttpRequestResponseType;
    constructor();
    get readyState(): number;
    get response(): unknown;
    get responseText(): string;
    get responseURL(): string;
    get status(): number;
    get statusText(): string;
    open(method: string, url: string | URL, async?: boolean, _username?: string | null, _password?: string | null): void;
    setRequestHeader(name: string, value: string): void;
    getResponseHeader(name: string): string | null;
    getAllResponseHeaders(): string;
    abort(): void;
    send(body?: BodyInit | Record<string, unknown> | null): void;
}
export {};
